### ISSUE TITLE
getting pixel values "around" the current pixel?

### ISSUE THREAD

**Issue by Pomax** [nleseul/obs-shaderfilter#12]
Is there a way to get pixels around the current pixel value, for more informed tone curves, blurring, etc?

**Comment by davboecki** [comment]
Look at https://github.com/nleseul/obs-shaderfilter/issues/1 for different blur filters, which all access pixels around the current pixel.

**Comment by Pomax** [comment]
Those should probably be added as an example, so that the README.md can link to them going "if you want to work with more than a single pixle (e.g. convolution filters), have a look at `link`".

**Comment by Pomax** [comment]
probably only worth closing if there's a new issue for "adding/linking to an example of convolution in the README"? Otherwise keeping it open (and retitling it) would be better.
